# MYSQL参数配置
DB_HOST     = "localhost:3306"
DB_USERNAME = "root"
DB_PWSSWORD = "Root@123"
DB_DATABASE = "okc"

create:
	$(if $(table), \
	./migrate create -ext sql -dir ./migration -seq $(table) \
	, echo table not define , please define table=xxx)

up:
	./migrate --path ./migration --database="mysql://$(DB_USERNAME):$(DB_PWSSWORD)@tcp($(DB_HOST))/$(DB_DATABASE)" -verbose up

down:
	./migrate --path ./migration --database="mysql://$(DB_USERNAME):$(DB_PWSSWORD)@tcp($(DB_HOST))/$(DB_DATABASE)" -verbose down

drop: 
	./migrate --path ./migration --database="mysql://$(DB_USERNAME):$(DB_PWSSWORD)@tcp($(DB_HOST))/$(DB_DATABASE)" -verbose drop

goto: 
	$(if $(v), \
	./migrate --path ./migration --database="mysql://$(DB_USERNAME):$(DB_PWSSWORD)@tcp($(DB_HOST))/$(DB_DATABASE)" -verbose goto $(v) \
	, echo goto version not define , please define v=xxx)
	
.PHONY: up, down, create, drop, goto