# 配置文件
MYSQL:
  DATABASE_NAME: dfproxm
  DATABASE_HOST: "localhost"
  DATABASE_PORT: 3306
  DATABASE_ROOT: root
  DATABASE_PASSWORD: "root"

REDIS:
  DATABASE_HOST: localhost
  DATABASE_PORT: 6379
  DATABASE_PASSWORD: ""

EMAIL:
  USERNAME: "gz341500@163.com"
  PASSWORD: "a8724513"
  SERVER_HOST: "smtp.163.com"
  SERVER_HOST_PORT: "smtp.163.com:465"

MONGODB:
  DATABASE_USERNAME: "mongo"
  DATABASE_PASSWORD: ""
  DATABASE_NAME: "admin"
  DATABASE_HOST: "localhost"
  DATABASE_PORT: 27017